name: Release on CI Pass

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      
      - name: Run tests
        run: go test ./...

  release:
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      
      - name: Extract version
        id: version
        run: |
          VERSION=$(grep 'const VERSION' cmd/main.go | sed -E 's/.*"([^"]+)".*/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$VERSION" >> $GITHUB_OUTPUT
      
      - name: Check if tag exists
        id: check_tag
        run: |
          if git ls-remote --tags origin | grep -q "refs/tags/v${{ steps.version.outputs.version }}$"; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Install UPX
        if: steps.check_tag.outputs.exists == 'false'
        run: |
          sudo apt-get update
          sudo apt-get install -y upx-ucl
      
      - name: Build binaries
        if: steps.check_tag.outputs.exists == 'false'
        run: chmod +x build.sh && ./build.sh
      
      - name: Prepare release assets
        if: steps.check_tag.outputs.exists == 'false'
        run: |
            mkdir -p release
            VERSION=${{ steps.version.outputs.version }}
            
            # Rename binaries with platform/arch info
            cp bin/linux/amd64/gobackup-v${VERSION} release/gobackup-v${VERSION}-linux-amd64
            cp bin/darwin/arm64/gobackup-v${VERSION} release/gobackup-v${VERSION}-darwin-arm64
            cp bin/darwin/amd64/gobackup-v${VERSION} release/gobackup-v${VERSION}-darwin-amd64
            
      - name: Create release
        if: steps.check_tag.outputs.exists == 'false'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            gh release create v${{ steps.version.outputs.version }} \
            --title "Release v${{ steps.version.outputs.version }}" \
            --generate-notes \
            release/*